name: Publish distributions to PyPI and TestPyPI
on:
  release:
    types:
      - released

jobs:
  build-and-publish:
    name: Build and publish distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install wheel
      run: >-
        pip install wheel

    - name: Build
      run: >-
        python3 setup.py sdist bdist_wheel

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
